baseurl = "//www.breizhcamp.org/"
title = "BreizhCamp - 9ème édition - 20, 21 et 22 Mars 2019"
theme = "hugo-universal-theme"
languageCode = "fr"
defaultContentLanguage = "fr"
# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink = "/blog/"
    author = "BreizhCamp"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    # et orange !
    style = "orange"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contact@breizhcamp.org"

    copyright = """<p>Copyright (c) 2015-2018, BreizhCamp team</p>
        <p><a href="https://github.com/breizhcamp/website">Améliorer ce site</a></p>
        """
    date_format = "2 January 2006"
    logo = "img/logo.png"

	#logo url for social network
    social_logo = "img/carousel/code-busters.png"
    social_locale = "fr_FR"
    social_twitter = "@breizhcamp"


[params.breizhcamp]
    edition_year = "2019"
    edition_date_place = "20, 21 et 22 Mars à Rennes"
    edition_date_start = "2019-03-20"
    edition_date_end = "2019-03-22"
    previous_editions = ["2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"]
    programme_get_talks_method = "cfp_api"  # static | cfp_api

[[params.social_links]]
    type = "twitter"
    title = "Twitter"
    url = "https://twitter.com/breizhcamp"

[[params.social_links]]
    type = "googleplus"
    title = "Google Plus"
    url = "https://plus.google.com/103143580610870538195"

[[params.social_links]]
    type = "youtube"
    title = "YouTube"
    url = "https://www.youtube.com/user/BreizhCamp"

[[params.social_links]]
    type = "flickr"
    title = "flickr"
    url = "https://www.flickr.com/photos/149773585@N06/albums"


[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "CFP"
    url  = "https://breizhcamp.cfp.io"
    image= "https://breizhcamp.cfp.io/images/logo.png"
    label= '<span class="label label-success">Ouvert</span>'
    weight = 1

[[params.menu]]
    name = "Conférence"
    url  = "/conference"
    weight = 2

#[[params.menu]]
#    name = "Billetterie"
#    url  = "https://www.billetweb.fr/breizhcamp-2019"
#    weight = 2

#[[params.menu]]
#    name = "Programme"
#    url  = "/conference/programme/"
#    weight = 3

[[params.menu]]
    name = "Venir"
    url  = "/venir/"
    weight = 4

[[params.menu]]
    name = "Sponsors"
    url  = "/sponsors/"
    weight = 8

#[[params.menu]]
#   name = "FAQ"
#    url  = "/faq/"
#    weight = 9

[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 10

[[params.menu]]
    name = "Equipe"
    url  = "/team/"
    weight = 11

[[params.menu]]
    name = "Asso"
    url  = "/asso/"
    weight = 12

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p>
        Lorem Ipsum
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    title = "La conférence à l'ouest"
    subtitle = """Le BreizhCamp, c'est 3 jours de conférence à Rennes.
    Créé en 2011 à l’initiative du BreizhJUG, nous sommes en cours de planification de la 9ème edition.
    Le BreizhCamp propose de se faire rencontrer une communauté de développeurs et d’experts, avec un contenu à la carte sur plus de 100 thèmes présentés.
    Chaque participant est libre de suivre les sujets qui ont retenu son attention ou de préférer les ateliers pour mettre en pratique les connaissances acquises.
    """

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "La conférence du grand ouest"
    # subtitle = ""

[params.see_more]
    enable = true
    # icon = "fa fa-transgender"
    title = "Une équipe dévouée"
    subtitle = "Sous la houlette de Canard Man, une équipe de bénévoles se met en 4 rien que pour vous !"
    # link_url = "#"
    # link_text = "L'asso"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    # title = "Our Clients"
    # subtitle = ""

# Les sponsors
[params.sponsors]
    enable = true
    # All sponsors are defined in their own files. You can find example items
    # at 'exampleSite/data/sponsors'.
    # For more informtion take a look at the README.
    title = "Sponsors & Partenaires"
    subtitle = "Le BreizhCamp n'est possible que grace au soutien de nos sponsors. N'hésitez pas à nous contacter pour devenir vous aussi sponsor de l'évenement."
    thankyou = "Un grand merci à tous nos Sponsors et Partenaires !"
    # Lister les sponsors
    show_list = true
    # Afficher les sponsors ou seulement des vignettes anonymes
    visible = true
    anon_nbr_platinum = 4
    anon_nbr_gold = 8
    anon_nbr_silver = 12
    anon_nbr_bronze = 24
    anon_nbr_meetgreet = 1
    anon_nbr_partenaire = 2


[params.recent_posts]
    enable = true
    title = "Blog"
    # subtitle = ""
